In [2]:
import numpy as np
np.__version__

'1.18.1'

In [7]:
# numpy에서는 ndarray

list_1 = [1,2,3]
print(type(list_1))

array1 = np.array(list_1)
print(array1)
print(type(array1))
print(array1.shape)

array2 = np.array([[1,2,3],
                  [4,5,6]])
print(array2)
print(type(array2))
print(array2.shape) # 행, 열
print(array2.ndim) # 차원
print(array2.size) # 전체 요소 개수

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
(3,)
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
6


In [12]:
# ndarray type

print(array1.dtype)
print(array2.dtype)

array3 = np.array([1,2,3.0])
print(array3.dtype) # 타입이 섞여있을 때는 큰 타입으로

array4 = np.array([1,2,'test'])
print(array4.dtype) # unicode 체계

# list는 여러 타입이 들어오면 각각 됨
# ndarray는 전체를 한 타입으로 처리 -> 타입을 맞춰주는 것이 좋음

int32
int32
float64
<U11


In [3]:
# ndarray type 변경

array_int = np.array([1,2,3])
print(array_int)
print(array_int.dtype)

array_float = array_int.astype('float64')
print(array_float)
print(array_float.dtype)

array_float2 = np.array([1.1,2.1,3.1], dtype = np.int64)
print(array_float2)
print(array_float2.dtype)

[1 2 3]
int32
[1. 2. 3.]
float64
[1 2 3]
int64


#### 연습 01

In [5]:
a_array = np.array([[[1,2],
                    [3,4]],
                   [[5,6],
                   [7,8]]])
print(a_array)
print("배열의 크기 : {}".format(a_array.shape))
print("배열의 차원 : {}".format(a_array.ndim))
print("배열의 개수 : {}".format(a_array.size))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
배열의 크기 : (2, 2, 2)
배열의 차원 : 3
배열의 개수 : 8


In [6]:
# 순차적인 수로 ndarray 생성

seq_array = np.arange(10)
print(seq_array)
print(seq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [13]:
# 0으로 채워서 ndarray 생성

zero_array = np.zeros((3,2), dtype=np.int32) # 'int32'로 해도 됨
print(zero_array)
print(zero_array.shape)

# 1로 채워서 ndarray 생성

ones_array = np.ones((3,2)) # default는 float
print(ones_array)
print(ones_array.dtype)

# 0,1 이외의 수로 채워서 ndarray 생성

full_array = np.full((3,2),5) #default는 int32
print(full_array)
print(full_array.dtype) 

# 랜덤 수로 채워서 ndarray 생성

rand_array = np.random.rand(3,2)
print(rand_array)

rand_array2 = np.random.randint( 2,10,size=(3,2)) # 2~10 사이
print(rand_array2)

[[0 0]
 [0 0]
 [0 0]]
(3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64
[[5 5]
 [5 5]
 [5 5]]
int32
[[0.19739327 0.36074766]
 [0.77234571 0.2823182 ]
 [0.65819702 0.64106924]]
[[2 3]
 [9 4]
 [7 9]]


#### 연습 02
1,2,3,...,50이 담긴 배열 생성

In [14]:
b_array = np.arange(1,51)
print(b_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [16]:
# ndarray 차원 변경

arr = np.arange(10)
print(arr)

arr2 = arr.reshape(2,5)
print(arr2)

arr3 = arr.reshape(5,2)
print(arr3)

arr4 = arr2.reshape(5,2)
print(arr4)

# arr5 = arr.reshape(3,3) 에러

# 차원 자동으로 변경시키기
arr6 = arr.reshape(2,-1) # 명확하지 않으면 -1
print(arr6)

arr7 = arr.reshape(5,-1)
print(arr7)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
# list type으로 바꾸기

arr = np.arange(8)
arr3d = arr.reshape(2,2,2)
print(arr3d)
arr3d_list = arr3d.tolist()
print(arr3d_list)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [19]:
# reshape은 같은 모양으로 만들어줌 - 실행 결과가 똑같음
# 여러 복잡한 데이터들의 모양을 통일 시켜주고자 할 때 reshape이용

arr_2 = arr.reshape(-1,1)
print(arr_2, arr_2.shape, arr_2.ndim)

arr3d_2 = arr3d.reshape(-1,1)
print(arr3d_2, arr3d_2.shape, arr3d_2.ndim)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1) 2
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1) 2


### 인덱싱 & 슬라이싱 & 팬시인덱싱 & 불린인덱싱

#### 인덱싱

In [24]:
# 인덱싱
array = np.arange(start=1, stop=10)
v = array[2]
print(v)

# 수정하기
array[2]=9
print(array)
print(v)

# 2차원 인덱싱
array_2 = np.array([[1,2,3],
                   [4,5,6]])
print(array_2)

print(array_2[0])
print(array_2[0][0])
print(array_2[0,0])  # [0][0]과 같음

array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[1,0])

3
[1 2 9 4 5 6 7 8 9]
3
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
4


#### 슬라이싱

In [25]:
# 슬라이싱
array = np.arange(1,10)
print(array[1:3])
print(array[3:])

[2 3]
[4 5 6 7 8 9]


In [32]:
# 2차원 슬라이싱
array = np.arange(1,10).reshape(3,3)
print(array)

print(array[0:2,0:2])
print(array[1:3,0:3])
print(array[1:3,:])
print(array[:,:])
print(array[:2,1:])
print(array[0].shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
(3,)


#### 팬시 인덱싱
인덱스의 목록을 여러개 가지고 오는 것 - [ [ ] ]

In [40]:
array = np.arange(1,10)
print(array)

# 1차원 팬싱
print(array[[2,4,7]])

# 2차원 팬싱
array = array.reshape(3,3)
print(array)
print(array[[0,1],2]) # 0행, 1행의 2열
print(array[[0,1],0:2])
print(array[[0,1]])

[1 2 3 4 5 6 7 8 9]
[3 5 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


#### 불린 인덱싱

In [43]:
array = np.arange(1,10)
print(array>5)
print(array[array>5])

[False False False False False  True  True  True  True]
[6 7 8 9]


#### 연습

In [47]:
name = np.array(['홍길동','박철수','이혜수','임유리','김영원'])
name_score = np.array([[60,60],[70,70],[80,80],[90,90],[100,100]])
print(name_score)

print(name=='홍길동')
print(name_score[name=='홍길동'])

[[ 60  60]
 [ 70  70]
 [ 80  80]
 [ 90  90]
 [100 100]]
[ True False False False False]
[[60 60]]


#### 연습 
각 사람의 BMI 지수 구하기 몸무게/(키*키)

In [55]:
drive_path = r'c:/Apps/temp/'
data = np.loadtxt(drive_path+'height_weight.txt',delimiter=',') # 구분자
print(data)

height = data[0]
weight = data[1]
bmi=[]

for i in range(len(height)):
    bmi.append(weight[i]/(height[i]**2))
print(bmi)


[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]
[0.0021371531035633117, 0.002707018468325884, 0.002586122448979592, 0.0024206528846637495, 0.0016035434227896761, 0.0020144861928474422, 0.0023143920947975003, 0.0021697206508280212, 0.0023620287912158064, 0.002559220998096189]


### 정렬

In [58]:
# 정렬 1 : 원래 데이터 수정 x, 새롭게 생성
org_array = np.array([3,5,2,1,9])
sort_array = np.sort(org_array)
print(org_array)
print(sort_array)

# 정렬 2: 원래 데이터를 수정
org_array.sort()
print(org_array)

# 반대로 정렬
reverse_array = np.sort(org_array)[::-1]
print(org_array)
print(reverse_array)

[3 5 2 1 9]
[1 2 3 5 9]
[1 2 3 5 9]
[1 2 3 5 9]
[9 5 3 2 1]


In [63]:
# 축으로 정렬 - 행방향
array = np.array([[8,12],[7,1]])
sort_array = np.sort(array, axis=0)
print(sort_array)

# 축으로 정렬 - 열방향
sort_array = np.sort(array, axis=1)
print(sort_array)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [64]:
org_arr = np.array([3,5,2,1,9])
sort_arr = np.sort(org_arr)
sort_index = np.argsort(org_arr)
print(sort_arr)
print(sort_index)

[1 2 3 5 9]
[3 2 0 1 4]


In [66]:
# argsort 활용

name = np.array(['홍길동','박철수','이혜수','임유리','김영원'])
name_score = np.array([79,95,84,98,88])

sort_index = np.argsort(name_score)
name[sort_index] # 성적순으로 이름 출력

array(['홍길동', '이혜수', '김영원', '박철수', '임유리'], dtype='<U3')

In [68]:
# ndarray 연산

array = np.arange(5)
print(array + 100)
print(np.add(array,array))
print(array==array)

[100 101 102 103 104]
[0 2 4 6 8]
[ True  True  True  True  True]
